[package]
name = "xtask_bench"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
xtask = { path = '../', version = "0.0" }
rome_benchmarker = { path = "../../crates/rome_benchmarker", version = "0.0.0" }

pico-args = "0.4.2"
regex = "1.5.5"
ureq = "2.4.0"
url = "2.2.2"
ansi_rgb = "0.2.0"
